name: github action test

on:
  push:
    branches:
      - main

jobs:
  My-Deploy-Job:
    runs-on: ubuntu-latest
    steps:
      - name: hello 찍기
        run: echo "Hello World"

      - name: 여러명령어 넣기
        run: |
          echo "good"
          echo "morning"
